HelloDjango/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include


urlpatterns = [
#    path('admin/', admin.site.urls),
#    path('index/', views.index, name='index'),

     re_path(r'^admin/', admin.site.urls),
     re_path(r'^blog/', include('blog.urls',namespace='blog')),
     re_path(r'^account/',include('account.urls',namespace='account')),
]

account/urls.py
from django.conf.urls import url,re_path
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views

app_name='account'

urlpatterns = [
#    re_path(r'^login/$', views.user_login, name="user_login"),
    re_path(r'^login/$', auth_views.login, name="user_login"),
    re_path(r'^new-login/$', auth_views.login, {"template_name": "account/login.html"}),
    re_path(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}),
    re_path(r'^register/$', views.register, name="user_register"),

]

blog/urls.py
from django.conf.urls import url
from django.urls import path,re_path
from . import views

app_name='blog'
urlpatterns = [
    re_path(r'^$',views.blog_title, name='blog_title'),
    re_path(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput)
class Meta:
    model = User
    fields = ("username", "email")

def clean_password2(self):
    cd = self.cleaned_data
    if cd['password'] != cd['password2']:
        raise forms.ValidationError("Password do not match")
    return cd['password2']

account/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, RegistrationForm

def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user:
                login(request,user)
                return HttpResponse("Welcome you")
            else:
                return HttpResponse("Sorry, your username and password is not rigjht")
        else:
            return HttpResponse("Invalid login")

    if request.method == "GET":
        login_form=LoginForm()
        return render(request, "account/login.html", {"form": login_form})


def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save
            return HttpResponse("successfully")
        else:
            return HttpResponse("sorry,you can not register")
    else:
        user_form = RegistrationForm()
        return render(request, "account/register.html", {"form": user_form})

blog/views.py
from django.shortcuts import render

# Create your views here
# .

from django.shortcuts import render,get_object_or_404
from .models import BlogArticles


def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {"blogs": blogs})

def blog_article(request,article_id):
#    article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles,id=article_id)
    pub = article.publish
    return render(request, "blog/content.html", {"article":article,"publish":pub})

cmdb/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import HttpResponse
def index(request):
    return HttpResponse("Hello world!")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh_cn">
<head>
<!--    <meta http-equiv="X-UA-Compatible" content="IE==Edge">
-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/blog/content.html
<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
-->
{% extends "base.html" %}
{% block title %}blog article{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{article_id}}</h1>
</div>

<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="text-center>
        <span>{{ article.author.username }}
        </span>
        <span style="margin-left:20px">{{ publish }}
        </span>
        </p>
    </div>{{ article.body }}</div>
</div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>加油clark wang</p>
        <img width="200px" src="http://img0.imgtn.bdimg.com/it/u=1315791044,3791425400&fm=27&gp=0.jpg">

    </div>
</div>
{% endblock %}

templates/blog/titles.html
<!--
<!DOCTYPE html>
<html lang="zh_cn">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
-->
{% extends "base.html" %}
{% block title %}blog titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>my blog</h1>
</div>

<div class="row">
    <div class="col-xs-120 col-md-80">
        <ul>
            {% for blog in blogs %}
                <li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>加油clark wang</p>
        <img width="200px" src="http://img0.imgtn.bdimg.com/it/u=1315791044,3791425400&fm=27&gp=0.jpg">

    </div>
</div>
{% endblock %}

templates/footer.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
-->
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

templates/header.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
-->
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand"  href="http://www.itdiffer.com">
                <img src="{%static '/images/flower.jpg' %}" width="150px"
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="#">Logout</a> </li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">Login</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>